- .gitignore
- README.md
- backend.js
- parser.js
- test/test.js
- utility.js
need to write more tests to make sure this works.
It was some epically reckless coding.
> parsestream

- processors.js
- public/js/browser.js
- views/index.jade
fixes #230 
Could use styling improvements
> implemented basic rating graph

- web.js
> fix anon not affecting goal and not expiring

- package.json
- routes/matches.js
- routes/upload.js
> Re-enable cache

- README.md
- advquery.js
- db.js
- migrations/loader.js
- migrations/patch.js
- migrations/rating.js
- package.json
- processFullHistory.js
- processMmr.js
- public/css/yasp.css
- public/js/playerTrendsTables.js
- queries.js
- routes/players.js
- tasks/unparsed.js
- test/test.js
- views/match/match_index.jade
- web.js
> ratings schema change

- compute.js
- parser/src/main/java/yasp/Main.java
- processParse.js
- public/css/yasp.css
- sources.json
- utility.js
- views/match/match_chat.jade
- views/match/match_objectives.jade
- views/match/match_teamfights.jade
- views/player/player_counts.jade
fixes #393 
fixes #390 
fixes #389
> implemented firstblood, tower deny, participation

- public/css/yasp.css
- views/match/match_index.jade
- webpack.config.js
> added picks/bans for captains mode

- advquery.js
- fillPlayerData.js
- helper.js
- operations.js
- public/js/playerMatches.js
- queries.js
- routes/matches.js
- routes/players.js
- views/player/player.jade
- views/player/player_activity.jade
- views/player/player_advanced.jade
- views/player/player_counts.jade
- views/player/player_histograms.jade
- views/player/player_index.jade
- views/player/player_matches.jade
> Aggregation

- config.js
- processApi.js
- socket.js
- views/request.jade
useful if you haven't been captcha whitelisted
> added env var to optionally disable the captcha on the Request page

- config.js
- processParse.js
- socket.js
- utility.js
- views/match/match_teamfights.jade
- views/request.jade
resolves #442, also (accidentally) contains nocaptcha branch changes
> Betterstreaks

- config.js
- processParse.js
- public/css/dark.css
- socket.js
- sources.json
- views/match/match_details.jade
- views/request.jade
> smallchanges

- advquery.js
- compute.js
- views/match/match_chat.jade
- views/player/player_wordcloud.jade
created a second word cloud that shows only the words that YOU typed into all chat
> self word cloud

- routes/matches.js
- routes/players.js
- views/match/match.jade
- views/player/player.jade
added json dump of players/matches
> fixes #473

- aggregator.js
- compute.js
- skill.js
- views/player/player_advanced.jade
> fixes #503

- views/post.jade
This is only fixes the mixed indentation part of the issue.
> Fix #594 Change tab to spaces

- config.js
- parseManager.js
- parser.js
- proxy.js
- retriever.js
- web.js
sets default ports in config.js, and forces PORT to "" in development environment.
Services use PORT, then a more specific *_PORT.
> fixes #588

- java_parser/src/main/java/yasp/Main.java
@albertcui should review and merge.
> fixes #619

- compute.js
- fillPlayerData.js
merge cachepatch into tooltips
> Cachepatch

- dev/scratch.sh
- parser.js
> parserleak

- java_parser/src/main/java/yasp/Main.java
- parser.js
> fixes #598

- java_parser/src/main/java/yasp/Entry.java
- java_parser/src/main/java/yasp/EventStream.java
- java_parser/src/main/java/yasp/Main.java
I rather enjoy using yasp, so I figured I would see what's under the hood. Seems there have been some scary creatures growing there! Figured I'd help clean it a bit first. Explanation of each commit is below. You'll want to look at the individual commits to see what on earth is going on since so many lines have changes due to the first two commits.
1. [Replace tabs with spaces for consistency](https://github.com/yasp-dota/yasp/commit/6117f8741bdff43c0fc11b6c29dbd69f5cd32a46)
* There was a scattering of tabs and spaces in use. Consistency makes for happier coders.
2. [Consistent spacing between elements](https://github.com/yasp-dota/yasp/commit/ff80fc5a00dd47602bc2091e1ea67dd4c8335515)
* One could find statements like `if(true) {` `if (true){` `if(true){` and `if (true) {`
* Consistently …
> Java parser code cleanup

- test/test.js
- views/navbar.jade
- web.js
> remove pro tab

- advquery.js
- aggregator.js
- compute.js
- filter.js
- tasks/constants.js
- views/player/player.jade
- views/query.jade
implements item filter requested by @lomash
fixed a couple of caching bugs
> Item filter

- .gitignore
- README.md
- public/css/yasp.css
- views/match/match_positions.jade
also a small change to the readme
edit: and add swap files to the gitignore.  I can break this up if it's a problem.
tested this locally, didn't add any automated tests because the change is so trivial but i can look into it if it's a sticking point.
> Update hover state on positions page to better indicate how to interact with the heatmap

- public/js/buildMap.js
Moved radiant towers and barracks to more accurately represent their position on the map.
Radiant t1, t2 top, t2 bot, t1 mid, melee and ranged mid barracks.
#697
> Fix for issue #697

- views/player/player_records.jade
Don't even know if you want to have this feature, or if I implemented it correctly(don't have a computer I can test it on right now). Was just familiarizing myself a little bit with the codebase(I like this project and want to make more useful contributions in the future) and found this was easy to add.
p.s: do you guys hang out on some IRC server or something? Would love to help with stuff sometimes as a little side-project :)
> Add full date as title to "x days ago" on records page

- public/js/resize.js
- public/js/util.js
- public/js/yasp.js
- views/base_layout.jade
- views/match/match_performances.jade
- views/match/match_vision.jade
- views/player/player_wardmap.jade
fixes #605 
- Also fixes similar issues for player ward placement data
> Reloads/resizes heatmap on map resize. Fixes #605

- views/blog.jade
- views/faq.jade
Simply makes the curly-cue image on the faq and blog pages scale with viewport as requested in #539
> Make curly-cue image responsive

- compute.js
- json/tooltips.json
- views/match/match_farm.jade
fixes #808 
Added roshan count to the Farm tab, Distribution table
> Added roshan count

- _posts/one-year.md
> One Year Blog Post

- deploy.js
- processExpand.js
> fixes #862

- dev/accountHelper.js
- package.json
- public/index.html
- public/js/actions/index.js
- public/js/components/app.jsx
- public/js/components/todos.js
- public/js/reducers/yasp.js
- public/js/store.js
- webpack.config.js
Merging React branch into ranking branch since react code can live in parallel with master.
> basic react/redux tutorial

- views/match/match_teamfights.jade
> Replace unicode char with fontawesome.io

- views/match/match_index.jade
fixes #886 
Addresses yasp-dota/yasp#886
> Add message for players who abandoned the match.

- profiler.js
checking if steamids is not empty before starting to profile.
> fixed profiler requesting empty steamids

- analysis.js
Adds ring_of_aquila, ring_of_basilius and linken's shpere to Active items
Signed-off-by: WTFKr0 <thomas.kovatchitch@gmail.com>
> Change Item Active detection

- benchmarkMatch.js
- cacher.js
- dev/postgresTest.js
- getMatchRating.js
- getReplayUrl.js
- init-gce.sh
- parser.js
- playerCache.js
- queries.js
- routes/api.js
- sql/create_tables.sql
- utility.js
- views/match/match.jade
- views/match/match_analysis.jade
- views/match/match_benchmarks.jade
- views/player/player.jade
- web.js
- worker.js
fixes #923
Schema changes:
* `alter table matches drop column url;`
Reviewers:
@albertcui 
@vali19n
> initial implementation of match percentiles

- views/player/player_histograms.jade
- views/player/player_records.jade
- views/player/player_trends.jade
> fix wrong link ?

- buildMatch.js
- buildPlayer.js
- compute.js
- config.js
- dev/postgresToCassandra.js
- json/player_fields.json
- playerCache.js
- queries.js
- routes/api.js
- routes/matches.js
- routes/players.js
- sql/cassandra.cql
- test/test.js
- utility.js
- views/mixins/match_table.jade
- web.js
setup, refactors for storing player_matches in cassandra.
@albertcui please review (mergeable)
> Cassandra match

- public/css/yasp.css
> lighten footer of tables so team rows are delineated from last player

- views/carry.jade
> add support email, make pricing more prominent

- util/compute.js
- views/match/match_combat.jade
> #873 - Added totals to the "Damage Done/Taken" table on the match combat tab

- util/analysis.js
- util/compute.js
> Updated the late courier check to use the first purchase time.

- routes/donate.js
- svc/web.js
- util/utility.js
- views/thanks.jade
Skip checking DB on every load of a logged in user.
We almost never use anything in req.user besides account_id, which is what we save in the cookie anyway.
The only exception was req.user.cheese, for displaying the total amount of cheese.  I removed this.
> Fast requser

- json/tooltips.json
- store/queries.js
- svc/cacher.js
- svc/parser.js
- views/rankings.jade
fixes #1017 
merge when ready to deploy new rankings (will reset existing ones)
> new rankings

- routes/api.js
Reviewers:
@bguzryanto 
@albertcui 
@Marvizm
> implement rankings/benchmarks apis

- dev/allMatches.js
- store/queries.js
Rewrite all matches script for use in filling match gaps
`node dev/allMatches 2112966257 2115500573`
> rewrite allmatches for cassandra

- dev/postgresToCassandra.js
- sql/cassandra.cql
- sql/create_tables.sql
- store/buildPlayer.js
- util/aggregator.js
- util/compute.js
We don't use this field for anything.
> remove match pgroup

- util/benchmarks.js
@nicholashh 
I made all benchmarks per_min
> per_min every benchmark

- README.md
- config.js
- routes/api.js
- scripts/deploy.sh
- sql/create_tables.sql
- store/buildPlayer.js
- store/playerCache.js
- store/queries.js
- svc/web.js
- svc/worker.js
- test/test.js
- util/filter.js
- util/utility.js
- views/query.jade
Improve /api/players endpoints to return more focused results.
Cassandra is now required.
> New player api

- routes/api.js
- store/playerCache.js
> implement limit/offset for players/matches

- java_parser/src/main/java/yasp/Main.java
Thread pool to allow multiple parallel requests on parseserver
> use java thread pool

- config.js
- sql/create_tables.cql
- sql/create_tables.sql
- store/buildMatch.js
- store/queries.js
- svc/cacher.js
- views/match/match.jade
- views/mixins/ads.jade
Schema updates:
```
ALTER TABLE player_matches ADD ability_upgrades_arr text;
```
```
CREATE TABLE match_rating(
match_id bigint PRIMARY KEY,
rating int,
num_players int
);
ALTER TABLE player_matches ADD ability_upgrades_arr integer[];
```
> add back ability upgrades column, remove match percentile

- .travis.yml
- routes/api.js
- svc/fullhistory.js
- svc/web.js
- views/player/player.jade
> fullhistory button

- store/buildMatch.js
- store/queries.js
- views/mixins/hero_td.jade
- views/player/player.jade
> show pro player names

- sql/create_tables.sql
- svc/worker.js
- util/utility.js
> add items to db

- views/query.jade
Various adjustments to the query form for better visual consistency. See each commit message for exact changes as they are broken down discretely for review.
Before: http://i.imgur.com/pomSAgQ.png
After: http://i.imgur.com/D7utQLk.png
> Query form alignment and styling

- views/query.jade
Reapply changes from #1222 after failed merge.
> Query form remerge

- Dockerfile
- docker-compose.yml
- index.js
* Change working directory from /usr/src/yasp to /usr/src
* Update to Node 6.6.0
Reviewers:
@dartharaknus
> update working directory

- routes/api.js
Return an array of bucketed counts.
Demo:
http://hchung.westus.cloudapp.azure.com:5000/api/players/88367253/histograms/last_hits
Reviewers:
@mike-robertson
> histogram counts on server

- routes/api.js
- store/queries.js
- svc/retriever.js
- util/filterDeps.js
- util/utility.js
Fixes and improvements for API endpoints.
* Sanitize inputs to prevent Cassandra errors due to nonexistent columns
* Clean up code determining what columns to project
* API semantics change: supplying the `project` parameter array now replaces the defaults for /player/matches endpoint
* Formatting code for eslint
Reviewers:
@albertcui 
@mike-robertson
@nicholashh
> API Improvements

- views/match/match_cosmetics.jade
* Adds link to cosmetic items.
Reviewers:
@albertcui
> Loot Market

- package.json
- store/buildStatus.js
- store/queries.js
Reviewers:
@albertcui 
@nicholashh
> add telemetry for visitor_matches

- public/js/generateCharts.js
- util/compute.js
- util/utility.js
Code with a little duplication, since this will be thrown away in a few weeks.
I tried to use the function from utility but I should be missing something.
require('utility') from generateCharts doesn't work, maybe because it's in another folder. I tried some variations as well but without success.
I'd be glad if someone know how to fix that. Otherwise, maybe it's better to accept just the generateCharts change.
> XP graph label in format: XP - Level L

- config.js
- svc/scanner.js
Reviewers:
@albertcui 
@nicholashh
> simplify scanner

- config.js
- svc/web.js
fixes #1319 
Need to set COOKIE_DOMAIN in GCE config
> use cross domain cookie

- store/queries.js
fixes #1316 
Merge before 2017-01-01
> remove negative points for losses

- util/utility.js
Reviewers:
@albertcui 
@nicholashh
> make conversion functions return strings

- svc/web.js
> https proxy for cosmetics

- package.json
- routes/spec.js
- util/compute.js
- util/utility.js
fixes #1328 
This is a breaking change to certain fields in /matches and /players/{account_id}/wardmap, hence the major version bump.
UI will be need to be updated to handle both cases (object as well as array position data) during the transition.
> Remove generatePositionData from core

- package.json
- routes/spec.js
Endpoint returning a list of pro players.
> add proPlayers/proMatches endpoint

- config.js
- routes/spec.js
- sql/create_tables.sql
- store/buildMatch.js
- store/cassandra.js
- store/queries.js
- test/test.js
- util/utility.js
Starts collecting data for #1264 and #1303 
Schema updates:
```
CREATE TABLE public_matches (
match_id bigint PRIMARY KEY,
match_seq_num bigint,
radiant_win boolean,
start_time integer,
duration integer,
avg_mmr integer,
num_mmr integer
);
CREATE TABLE public_player_matches (
PRIMARY KEY(match_id, player_slot),
match_id bigint REFERENCES public_matches(match_id) ON DELETE CASCADE,
player_slot integer,
hero_id integer
);
CREATE INDEX on public_player_matches(hero_id);
```
> initial implementation of public match sample

- dev/getMatch.js
- dev/getMatchesSeq.js
- dev/reParse.js
- package.json
- processors/processLogParse.js
- scripts/cycler.py
- scripts/gce.sh
- scripts/retriever.sh
- store/queries.js
- svc/backupscanner.js
- svc/fullhistory.js
- svc/parser.js
- util/utility.js
> Whitelist log event types

- package.json
- routes/spec.js
fixes #1264 
UI will need to be built separately.
> initial implementation of publicmatches and publicheroes

- processors/populate.js
- processors/processExpand.js
- sql/create_tables.cql
- sql/create_tables.sql
- sql/migrations.cql
- sql/migrations.sql
- svc/parser.js
> Add log of rune pickups

- package.json
- routes/spec.js
- store/search.js
fixes #1382 
Reviewers:
@FaridAhamat
> implement similarity option

- sql/create_tables.cql
- util/compute.js
- util/utility.js
> Roaming lane [WIP]

- routes/playerFields.json
- routes/spec.js
- util/utility.js
> add radiant/dire count, gpm/xpm with peers

- routes/spec.js
This PR adds some more depth to the example responses in the docs and clears up a bit of language.
> some doc changes

- routes/spec.js
> include radiant_win in players/:account_id/matches

- routes/spec.js
- svc/mmr.js
- util/getGcData.js
- util/getMMStats.js
- util/utility.js
Allow passing noRetry to getData for /replays endpoint so we don't spam requests to retrievers
> make array passing to getData part of object

- sql/create_tables.sql
- sql/migrations.sql
- svc/worker.js
Get primary attribute, melee/ranged and roles
> ingest hero attribute data

- processors/processExpand.js
- sql/create_tables.cql
- sql/migrations.cql
- store/queries.js
- svc/parser.js
fixes #1175 
repick data doesn't always appear to be present
> add randomed, repicked, predicted victory

- dev/skillToCassandra.js
- routes/spec.js
- sql/create_tables.cql
- sql/create_tables.sql
- sql/migrations.cql
- sql/skill.sql
- store/buildMatch.js
- store/queries.js
- svc/skill.js
- util/utility.js
* Move match skill data to Cassandra (store in skill property in matches and player_caches table)
* Need to add match column to matches table (done)
* Need to run migration script `skillToCassandra`
* currently about 437 million matches in the match_skill table
* after running this that table can be dropped (about 50GB currently)
* Might want to dump the match_skill table and put it in GCS or something before we drop just to have a backup (I took a snapshot of the disk so we prob don't have to do this)
> initial implementation of cassandra skill

- package.json
- routes/spec.js
- store/queries.js
fixes #443 
IDK about the badges, but at least this implements the leaderboards
> implement top 100 records endpoints

- sql/create_tables.sql
- sql/migrations.sql
- store/queries.js
- store/search.js
fixes #1440 
Sample search output:
```
[
{
"account_id": 220617010,
"avatarfull": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/dd/dd5e14457b6504825a3c3c44ceb2be16c1c4706b_full.jpg",
"personaname": "Ego1sT",
"last_match_time": "2017-04-17T00:41:41.000Z",
"similarity": 1
}
]
```
> add last match time column to players

- config.js
- docs/feed.md
- manifest.json
- package.json
- store/queries.js
- svc/parser.js
- svc/scanner.js
- svc/socket.js
This PR creates a web socket server that allows users to subscribe to team IDs, league IDs, or player IDs that have signed up for OpenDota, and receive socket messages when a new match is scanned or parsed for those IDs.
> Create socket service

- processors/performanceOthers.js
it seems that my previous impl was wrong in the base gold :P
> greevils greed 7.06

- processors/processExpand.js
Removed some code related to tracking starting items via actions
Please, check this!
https://github.com/odota/parser/pull/12
> removed item purchases tracking via actions

- processors/populate.js
- processors/processExpand.js
> log chatwheel events

- routes/spec.js
There are several places in the code where type `array` is not followed with `items` declaration. So I added definition according to this response https://api.opendota.com/api/matches/3170212000. 
NB: I change the type of `permanent_buffs` to object since its value is `null`, not `[]`.
> Fix array type definition

- routes/spec.js
https://github.com/odota/core/issues/1502
> change type number to integer

- .gitattributes
https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings
> Add .gitattributes to force LF on Windows

- package-lock.json
- package.json
- routes/spec.js
- sql/create_tables.sql
- store/queries.js
* Storing rankings in postgres, not Redis
* Removed quarterly reset
* Increased MMR scaling factor from 7 to 8
* Dividing all scores by ratingMin to reduce range
> postgres-based ranking

- dev/bootstrapMmr.js
- dev/mmrToPostgres.js
- routes/spec.js
- sql/create_tables.sql
- store/buildMatch.js
- store/queries.js
- svc/mmr.js
- svc/parser.js
Should save another ~150MB of redis memory, and allow easier joins for current MMR values
> Move current MMR values from redis to postgres

- README.md
- config.js
- routes/spec.js
Also made a small update to the README
> Added Player Cache Config Option

- routes/spec.js
- store/queries.js
fixes #1525 
Higher resolution avatars on /peers
> resolve #1525

- routes/spec.js
- store/queries.js
- test/test.js
New endpoints are:
/teams/{teamId} for one team's data
/teams/{teamId}/matches for a team's matches
/teams/{teamId}/players for players who have played for that team
/teams/{teamId}/heroes for heroes the team has played
> implement team data endpoints

- routes/objects.js
- routes/spec.js
- test/test.js
@Luchanso
Implements:
/heroes/{heroId}/matchups: returns games played and wins against all other heroes (for pro matches)
/heroes/{heroId}/matches: return most recent games played with this hero
/heroes/{heroId}/durations: return games played and wins for each bucket of 5 minutes
/heroes/{heroId}/players: return the players who have played the most games on this hero
> implement hero data endpoints

- routes/spec.js
KDA for matches tab https://github.com/odota/ui/pull/1247
@howardchung
> Add KDA for /heroes/:hero_id/matches

- sql/create_tables.sql
- sql/migrations.sql
- svc/worker.js
- util/utility.js
fixes #1506 
Valve removed the GetTeamInfo endpoint, so replacing with GetTeamInfoByTeamID.
Also adding team logos to the database.
> update team ingestion

- routes/spec.js
fixes #1548 
For issue #1548. Is it OK to add notable_players.team_id and teams.team_id to GROUP BY like this?
> Add "is_current_team_member" to teams/{team_id}/players api endpoint

- processors/createParsedDataBlob.js
- processors/processDraftTimings.js
- processors/processMetadata.js
- routes/spec.js
- sql/create_tables.cql
- sql/create_tables.sql
- sql/migrations.cql
- sql/migrations.sql
- test/test.js
fixes #1531 
From the changes in the parser this outputs the picks and bans, heroes choose, player slots for the choosen heros, the time taken for each ban and pick, the order of the bans and picks (automatically), the amount of extra time taken for each ban and pick.
I havent included checks for when it is a captain modes game.
I still havent figured out how the next stage in getting the extra information saved into the database and accessiable via the api and website ui.
The output once it has been processed looks like this:
`,"drafttimings":[{"order":1,"picksorban":"ban","team":3,"hero":27,"player_slot":null,"time":18,"extratime":130,"totaltimetaken":18,"extratimetaken":0},{"order":2,"picksorban":"ban","team":2,"hero":82,"player_slot":null,"time":24,"extratime":130,"totaltimetaken":24," …
> Add draft timings

- routes/params.js
- routes/spec.js
Partner request for https://github.com/odota/ui/pull/1324
> An attempt at implementing the filter_gamesplayed feature!

- store/queries.js
- svc/herostats.js
preliminary changes, still need testing.
Also need to clear old hero rankings `TRUNCATE TABLE hero_ranking`
odota/web for public matches hero stats need to be updated to handle rank split instead of mmr split
> update hero rankings and herostats for medals

- processors/createParsedDataBlob.js
- processors/populate.js
- processors/processExpand.js
- processors/processTeamfights.js
- routes/spec.js
- sql/create_tables.cql
- sql/create_tables.sql
- sql/migrations.cql
- sql/migrations.sql
fixes https://github.com/odota/web/issues/1172
> Added ability targets to display in casts table

- routes/objects.js
fixes #1591 
Updated heroes schema for the endpoint: https://api.opendota.com/api/heroes.
> Update schema for Heroes

- routes/spec.js
Mostly based on information from this link: https://github.com/odota/core/wiki/JSON-Data-Dump. Some of the info is old, so I didn't fill out everything, just things I was very confident in.
> Added information to the API descriptions

- config.js
- manifest.json
- sql/create_tables.sql
- sql/migrations.sql
- store/buildStatus.js
- store/queries.js
- svc/parser.js
- svc/scenarios.js
- util/scenariosUtil.js
- util/utility.js
collecting data for #1575 
Second part of this will be building the APIs to read data from these tables.
Scenarios:
-Item timings for all heroes and all items that cost at least 2000 gold. Timings are  7.5, 10, 12, 15, 20, 25 and 30 minutes. e.g. Anti-Mage buys BF before minute 12.
-How often a player "pings". How does utilizing the ping feature impact a player's win rate? Does overusing this feature maybe lower team morale?
-The hero's lane role (safe, mid , offlane...). On which lane role does a hero have the best win rate?
-First Blood. What is a team's win rate if they get first blood in a match? How important is getting first blood?
-Courier Kill before minute 3.  What is a team's win rate if they get a courier kill before minute 3. How important is it to make sure your courier …
> [WIP] Scenarios

- svc/scenarios.js
- util/scenariosUtil.js
fixes https://github.com/odota/core/issues/1598
> Fix for exception in scenarios worker. Match.players is null

- store/queries.js
> Don't include pro in list of own matches with pro players

- routes/spec.js
- util/filter.js
- util/filterDeps.js
closes https://github.com/odota/web/issues/1403
> party size filter

- svc/teams.js
- svc/web.js
- util/utility.js
fixes https://github.com/odota/core/issues/1616
> Get team logos from steam's CDN if available

- manifest.json
- store/queries.js
- store/queue.js
- svc/counts.js
- svc/mmr.js
- svc/parser.js
move counts to separate worker
also moved code that queues matches for scenarios (@Argn0)
> move counts to separate worker

- svc/scenarios.js
- util/scenariosUtil.js
fixes https://github.com/odota/core/issues/1630
> Fix scenarios error and some refactoring

- routes/spec.js
- svc/apiadmin.js
- svc/web.js
- test/test.js
> whitelist routes from api

- routes/params.js
- routes/spec.js
Add missing path parameters in API spec
> Fix missing path parameters in API spec

- util/benchmarksUtil.js
It just occurred to me, that the value probably should be per minute.
> Change stuns per minute

- routes/spec.js
- sql/create_tables.sql
- store/queries.js
- svc/mmr.js
New pull request to fix git shenanigans. [Old PR](https://github.com/odota/core/pull/1865).
> Added Dota Plus subscription status to player profiles

- package-lock.json
- routes/spec.js
- sql/create_tables.sql
- svc/counts.js
> implement findMatch endpoint

- config.js
- package-lock.json
- store/buildSets.js
allow fetching a list of account_ids to track from a URL
> implemented tracked url

- processors/processDraftTimings.js
>  Implemented new calculation for the first draft. (Parser)

- routes/spec.js
* People often ask how to interpret the data provided the API, so i thought it might be useful addition to the docs.
> Added a note about dotaconstants to API spec introduction

- package-lock.json
- package.json
- svc/web.js
* This should fix client's with IPv6 address being rate limited based on the last hexadectet of the address
> updated method for getting client's ip address

- routes/spec.js
fixes #1907
added a url path to get parsed matches, limited by 100 & using less_than_match_id
> Get parsed matches

- package-lock.json
- package.json
- routes/spec.js
> Playersbyrank endpoint

- docker-compose.yml
- sql/init.sql
This PR fixes postgres tables not being correctly created on fresh installs
> Fix db creation

- processors/createParsedDataBlob.js
- processors/performanceOthers.js
- processors/populate.js
- processors/processExpand.js
- processors/processMetadata.js
Update bountyhunter & alchemist gold values
Re-enable performanceOthers
This pull request also requires the parser update
> Update to ingest new DOTA_ABILITY_LEVEL

- CONTRIBUTORS.js
- package-lock.json
- package.json
- routes/objects.js
- routes/spec.js
- test/test.js
Resolves https://github.com/odota/core/issues/1703
This doesn't fix the incorrect API definitions, but does fix parsing. So tools can be used to generate clients that are mostly correct.
This PR also adds a new dependency, I'm not sure the guidelines on adding those, but it adds https://www.npmjs.com/package/@apidevtools/swagger-parser in order to parse the spec in a unit test to ensure validity.
> Resolve swagger parsing issues

- routes/objects.js
- routes/params.js
- routes/spec.js
- test/test.js
Resolves #2350 
* Add endpoint for leagues/{leagueid}
* Add endpoint for leagues/{leagueid}/matches
* Add endpoint for leagues/{leagueid}/teams
> Add more league endpoints

- .gitignore
- routes/spec.js
Also add .DS_Store to .gitignore.
Just noticed some more inconsistencies between what I got from the API and the docs
> Add more documentation fixes for 'player' route

- routes/spec.js
* This allows querying more than 1000 teams
> Added pagination to teams endpoint

- routes/spec.js
- sql/create_tables.cql
- sql/create_tables.sql
- store/queries.js
* To be used in player overview page
This should work right? It is kinda hard to test the scanner stuff - if I understood it correctly all new matches originate from scanner
> Add match average rank

- routes/spec.js
Fixes https://github.com/odota/core/issues/2578
> Fix teams pagination

- routes/params.js
Reverts odota/core#2602
Looks like there's some exception with Swagger, reverting for now.
cc @mdiller if you want to fix and try again
> Revert "Additional documentation for '/players/{account_id}/matches'"

- processors/performanceOthers.js
I don't currently play Dota so can't test this change, But assuming they kept the innate ability named the same this should work as before.
> Update for patch 7.33 Greevils Greed changes

- routes/objects.js
- routes/properties.js
- routes/spec.js
Reverts odota/core#2654
reverting for now to unbreak the build, but WIP to include these fixes in another PR
> Revert "Fix Swagger Spec definitions"

- package-lock.json
```sh
npm update
npm audit fix
npm dedupe
```
> :arrow_up: npm update & dedupe & fix

- util/compute.js
Closes https://github.com/odota/core/issues/2668
> Change `kda` to have two decimal places

- config.ts
- routes/spec.ts
- svc/web.ts
- test/test.ts
- util/utility.ts
cc @albertcui 
Since I'm changing the Redis key name this will effectively reset all usage counts for the month.
We should also update docs and UI
> switch to daily rate limit

- routes/keyManagement.ts
Haven't actually tested this yet
> add year to usage data

- ecosystem.config.js
- index.ts
- store/queue.ts
- svc/scanner.ts
- svc/web.ts
- util/utility.ts
Direct all the services through the index.ts entry point so we only need one set of exception handlers.
> single entry point

- sql/create_tables.sql
- sql/migrations.sql
- svc/items.ts
- util/utility.ts
Closes https://github.com/odota/core/issues/2646
> Use new api endpoint for items
