public/js/playerMatches.js
Sorting by the played column attempts to sort based on the the human readable "time from now" which will never work as expected.
This pull request changes sorting to use the unix offset instead.
I didn't set up YASP to actually see if this pull request works, so please let me know if there are any issues.
=> Fixed sorting recent matches by played column

public/css/yasp_home.css, views/home.jade
Reduced bandwidth requirement for homepage by removing sections/background images.
@albertcui should review, I may have been a little heavy-handed.
Saves:
* 400KB, our mission section
* 430KB, positions map
* 400KB, details background image
=> reduced homepage weight

views/match/match_teamfights.jade
Currently the Teamfights page always shows levels like 9->9. Change that to just 9, but show actual changes like 9->10.
=> Show unchanged levels without arrow

views/match/match_combat.jade
Previously, when kill scores were equal, it would show Dire as winner.
Now it will show no winner.
Fixes issue #682.
=> Equal kill/death to show no winner

status.js
yasp crashes if there is no connection to PostgreSQL. This could happen if the SQL server crashes or goes down for maintenance.
The reason is that `count` is then undefined and has no attribute `rows`.
So far the commit displays a white page with a stacktrace. Might not be the most elegant way but the player pages behave the same way. Is there an easy way to make some pretty 500 error pages from the `status` module?
=> Fixed application crash in /status if PostgreSQL connection is lost.

README.md, config.js
I went through the process of building and running YASP on my Fedora machine. This patch adds a new init script to make it easier for anyone who tries the same thing after me. I also thought the instructions were a bit unclear in places
This also fixes an issue in the init script for Debian/Ubuntu. Since contextify (and possibly other dependencies) don't currently run under Node 4.0.0 which has recently been declared the stable version of Node (see https://github.com/brianmcd/contextify/issues/180).
For a more complete list of changes, see the comment to the commit.
=> Improvements to quickstart instructions

public/css/yasp.css
Hello, 
I decided to change a little bit the CSS for the footer of the website because, right now, I think it has one or two things that could be improved.
Current Footer 
====
**Desktop Version**
The only problem is about uneven padding. This results in the footer not getting centered.
A bit difficult to notice here but on the CSS you can see it. It was `padding: 1.3em 0 0 1em;` for no apparent reasons.
**Mobile/Small Screen Version**
The footer on mobile is not centered (not only because of the padding) and I think that the lists are not the best looking.
My improvement 
====
**Desktop**
Even Padding and the footer is now centered for real.
Again: a bit hard to notice from a picture.
**Mobile**
I removed the bullet points from the lists and centered them.
Let me know what you think …
=> Improved CSS for the footer

processExpand.js, sql/create_tables.sql, utility.js
Set up for #815 .
It seems like the only things we care about are aghs consumed and dusts applied.
=> track only modifiers applied to heroes

compute.js
I went over the chat in my last 50 games and added a few sentiment analysis values that did not get picked up by yasp.
Individual explanations:
- "hero": positive in general language, but value neutral in the context of the game.
- "gg": self explanatory?
- "salty": if "salt" counts, this probably should count as well.
- "autist" / "autism": always negative in the context of the game.
=> Add additional sentiment analysis values

config.js, scanner.js
on a small vps / lowmem instance the new ranker will crash redis (happened to me frequently), 
most people don't have alot of mmr data to begin with,
so the ranker shouldn't be enabled by default.
=> only add players to ranker queue when ENABLE_RANKER is set in config

views/heroes.jade
Should fix the issue in #994 
Before:
After:
=> #994 - Removed min-height from hero images on the benchmark page

views/mixins/match_table.jade, views/player/player.jade
Fixes the sort order of the skill column in the matches table as described in issue #875.
I don't really like hard coding the skills again, but I couldn't figure out how to make the skill constants available in views/player/player.jade
=> #875 - Correctly sort match skill in match tables

views/mixins/match_table.jade
Looks like the last merge lost some of the changes. This should fix the skills showing up as their IDs instead of English names (Normal, High, Very High).
=> Fix an issue with the skill sorting due to a merge issue

constants.js
Fixes the issue described in #801 
I assume json/abilities.json is grabbed from Valve. If so, we'll need to make sure we keep these updates the next time the abilities file is regenerated, or we'll need a way to add/augment the these files.
Let me know what you think.
=> #801 - Added SF shadowraze2 and shadowraze3 abilities

store/buildPlayer.js, store/queries.js, svc/parser.js, test/test.js, views/match/match_combat.jade
In a recent change I made the cleaning of the object row used for db insertion return a new object, rather than deleting the extra properties (thus mutating the original object).
Previously we then used this mutated object to pass as input to the parse job, which is larger than is strictly needed and thus increases Redis usage.
With this change I am now creating a new object to pass with minimal properties (match_id, replay_blob_key, and pgroup).
In `parser`, previously we extended the match object passed as input.  Now we use the `parsed_data` object generated from the parse directly.  We add back any properties from the input we still need `match_id, pgroup`.  
After parse completion, the parser service invokes `insertMatch` again.  `insertMatch` now attempts to re-populate the hero_id …
=> optimization to match object transferred to parse job

config.js, store/queries.js, svc/scanner.js
Steam API responses taking 15+ seconds lately.  This attempts to brute-force sequence numbers (100 per page), which allows us to make multiple requests in parallel.
The previous design required us to wait for a single call to return, then issued the next API call based on the last sequence number on the page.  This is the most economical design, but is extremely sensitive to slow API.
Reviewers:
@albertcui 
@nicholashh
=> fixes #300

public/js/actions/actions.js, routes/api.js, sql/cassandra.cql, svc/web.js
Add CORS header to API endpoints.
Allow frontend developers to be able to work with the production site data without needing to setup the entire stack locally
Reviewers:
@albertcui 
@gu3st
=> add CORS header

sql/cassandra.cql
Got the following helpful error message when setting up Cassandra.
> <stdin>:153:InvalidRequest: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
Decided to go with the keyword `USE` so we don't have to specify *yasp* everywhere in the `.cql` file.
=> USE created 'yasp' keyspace

svc/cacher.js
Increase weight of MMR in rankings.
Note, I rescaled the rankings to divide average match MMR by 100, then round down.  Matches with average MMR below 100 will score 0 points.
Merge shortly before the July 1 ranking reset (Q3)
=> Ranking algorithm update for Q3

svc/cacher.js
Ranking tweak:
* Base match MMR is now 1000 (matches with average below this will score 0 points for all players)
* Only players with non-zero scores will appear in rankings (essentially, rankings will only contain players who have won at least one game on a hero).
=> Rankings update

docker-compose.yml, docker/cassandra.dockerfile
Cassandra is mandatory now, so docker sompose should be launching it too.
Cassandra image itself does [not](https://github.com/docker-library/cassandra/blob/c3c26f2efdb9874dc5b3717662462e8ca0b2d944/3.7/docker-entrypoint.sh) support initing itself like Postgres one [does](https://github.com/docker-library/postgres/blob/bcfa58b2f0c971ad55f541f3fb868607cd391089/9.6/docker-entrypoint.sh#L79-L87), so [wrapper image](https://github.com/Daerdemandt/cassandra-docker-init) -- that adds self-initing like in Postgres container -- is used.
=> Added Cassandra support for Docker Compose

config.js, processors/processExpand.js, routes/api.js, store/buildSets.js, store/queries.js, svc/backupscanner.js, svc/parser.js, svc/requests.js, svc/scanner.js, tasks/getMatch.js, util/compute.js
Scales better as the number of tracked players increases.
Previous behavior is to load the ids from Redis into a JavaScript object, then check for membership in the object.  New behavior is to do the membership checks on the IDs directly against the zset.
Reviewers:
@albertcui 
@nicholashh
=> Use Redis zsets directly for determining match tracked status

README.md
This updates README.md to help people avoid two problems that I ran into while setting up Docker:
1. The API key and username/password do not have to be connected to the same account.
2. The logon will fail if the account has SteamGuard enabled.
=> Add clarification about API key and username

package.json, routes/spec.js
This replaces the existing publicHeroes endpoint which was not in production use and therefore comes with a semver bump to v11.0.0
Contains data for pro pick/ban/win rates and public pick/win rates in one call.
=> Hero stats endpoint

store/queries.js
avoid heavy load due to dark moon matches.
Also affects modes like AD, ARDM, but most people don't care about those modes anyway.  Parsing still works on request.
=> don't autoparse insignificant matches

routes/spec.js
Previously this returned a 500 error if any salt failed to fetch.
This was inflating the number of artificial 500 errors and also reducing effective throughput.
=> return successful replay salt fetches

store/queries.js
* This change adds a minimum average match rating for matches to be considered for rankings (currently 2000).
* This reduces redis memory usage
=> add minimum match rating for rankings

README.md
Hi guys, 
after trying to spin-up odota/core on linux and windows, I've decided to add instructions to README.md how to:
- install docker-compose on linux
- configure git in such way, that the UNIX style line endings are preserved on windows after checkout/commit. Otherwise docker/prepend.sh is not working and sometime later the linting (I think) is unhappy.
Regards 🍻 
Georgi
=> Add a couple more instructions to README.md

README.md, processors/processExpand.js
fixes #1445 
In opendota starting items aren't shown if they were bought before the start of the game (this may happen in all pick when player picked his hero, for example). Right now, opendota gets purchases from combat_log, but combat log events appear only after beginning of the match. However, events with type of "actions" exists during picks too, so i suggest moving purchase tracking from combat log to actions. This pull request changes processExpand, so that it generate purchase events from actions events, not from combat_log.
However:
- I tested it on json generating, but not on whole project
- It doesn't get hero name by slot as i don't know how to do this, but it isn't needed, is it? (you get slot by hero name anyway) 
`  const slot = ('slot' in e) ? e.slot : …
=> moved item purchases form COMBATLOG to actions

processors/processExpand.js
Fixes some of issue #726.  Tried to include comments with what everything does, let me know if anything is confusing.  I ran some diff tests on some games to check if it works, which I included below.  I think it might be easier to just run it on dev and compare games with prod though.
```javascript
When run on a game with no roshan kills there was no diff
Here is an example of a diff from a game where a ta died once with an aegis:
// Gyro kills
-"hero_kills": 6,
+"hero_kills": 5,
-"npc_dota_hero_templar_assassin": 2,
+"npc_dota_hero_templar_assassin": 1,
-"key": "npc_dota_hero_templar_assassin",          "time": 1250        },        {
// TA Killed by
-"npc_dota_hero_gyrocopter": 2,
+"npc_dota_hero_gyrocopter": 1,
// Teamfights
-"deaths": 9,
+"deaths": 8, …
```
=> Ignore aegis deaths

processors/processExpand.js
This is now filtered in the UI instead, meaning people who use the api will be able to see the other chatwheel events.
=> Remove Chatweel Filtering

routes/spec.js, svc/worker.js, util/utility.js
Implement new endpoint:
/live: Returns 100 matches with highest server_steam_id values from Valve GetTopLiveGame endpoint
Not implemented yet:
Getting detailed data including match_id from GetRealTimeStats endpoint
=> implement live games data ingestion/endpoint

svc/web.js
To go with (https://github.com/odota/web/pull/1416)
=> proxy layer to serve team logos over https

routes/objects.js
There is a few object fields I wasn't sure what they their purpose was, so I left them as is. I'm open to suggestions here, I think that I could add more examples to fields if we think they could be useful.
- the locked fields: 'is_locked' and 'locked_until'. I'm assuming this for a user's account but I'm not sure how it could be locked or for how long.
- 'fantasy_role' thought this could have been the position the players are in their team (position 0-4, or carry, mid, offlane, roaming/farming support, support respectively) 
- 'fh_unavailable' 
- 'cheese'. Most players had 0 for this with a few exceptions. 
- 'full_history_time'
=> Improved majority of object field descriptions.

package-lock.json, package.json
Reverts odota/core#1787
For some reason dependabot update are casuing node-steam to break due to updating package-lock
=> Revert "Bump eslint from 5.7.0 to 5.9.0"

sql/create_tables.sql, store/queries.js
Creating a new parsed_matches in order to store all parsed matches
This is for https://github.com/odota/core/issues/1907
First PR, a new table
Next PR will be for the API call
=> create new parsed_matches table

routes/spec.js, store/queries.js, util/utility.js
Aggregate item popularity for a specific hero, categorised into start of game, early game, mid game and late game items.
For use in [this feature](https://github.com/odota/web/issues/2478)
=> Item popularity endpoint

CONTRIBUTORS.js, processors/populate.js, processors/processExpand.js, routes/spec.js
Currently Items that can be stacked do not show up correctly in the items tab:
Changed to add copies of the item depending on the max charges and the current charges an item has.
=> Fixed items with charges not being added correctly to purchase log

routes/spec.js
Key was previously integer, but the server responses are strings. Causes deserialization error
fixes #2300
=> Changed data type for purchase_log key

routes/webhookManagement.js
Hello 👋 thank y'all for your wonderful service!
I was building something using webhooks but ran into an issue where after creating a new webhook, I was not returned any info about the created resource and was unable to reference it in the future.
This PR makes it so when you `POST` to create a new webhook, the newly created webhook is returned back to you, allowing you to know it's ID so to reference it later.
I didn't see any tests to update but please let me know if I missed anything!
=> Return webhook info on creation

CONTRIBUTORS.js, routes/spec.js
Fix to the issue here: https://github.com/odota/core/issues/2409
=> Fix documentation for '/players/{account_id}/rankings'

routes/webhookManagement.js
SO it turns out my previous PR was not working (which is why I asked about it's deployment status) and I looked into why today.
I was mistaken about the returned value from `insert`. [If no `returning` argument is provided](https://knexjs.org/#Builder-insert), it appears to return some `Result` object that has no actual info about the inserted rows, contrary to what I thought was happening.
<details>
<summary>Result object per local testing</summary>
```
Result {
command: 'INSERT',
rowCount: 1,
oid: 0,
rows: [],
fields: [],
_parsers: undefined,
_types: TypeOverrides {
_types: {
getTypeParser: [Function: getTypeParser],
setTypeParser: [Function: setTypeParser],
arrayParser: [Object],
builtins: [Object]
},
text: {},
binary: {}
},
RowCtor: null,
rowAsArray: false
}
```
</details>
So as it is …
=> return hook id from insert call

CONTRIBUTORS.js, routes/objects.js, routes/spec.js
The /players/{account_id} definition has the competitve_rank and solo_rank listed as strings but in the actual api response they are numbers. 
Reference https://api.opendota.com/api/players/83615933 
Wasn't sure whether to categorize them as numbers or integers as in the /players/{account_id}/ratings api def they are listed as integers but all other numbers in the /players/{account_id} response they are listed as numbers.
=> Added openapi friendly names for objects, fixed type bug

store/queries.js, util/utility.js
The old average rank function was made for mmr, so it didn't account for medal algebra, causing ranks such as Guardian 8 to appear.
=> fix average medal calculation

routes/params.js
Hey! I've been using the api for a while and this particular endpoint `/players/{account_id}/matches` has been lacking some important documentation. This is just an update to the swagger api documentation to make it a lot more clear how to use the `project` field for this endpoint. I wasn't able to get my docker to behave properly to run odota core but I made these changes to the swagger api json file and tested it using odota/docs, and it looks much more usable now (see below). I'm pretty sure this doesn't affect any of the api functionality but again I wasn't able to test that. Let me know if you want me to make any changes!
[Endpoint Documentation](https://docs.opendota.com/index.html#tag/players%2Fpaths%2F~1players~1%7Baccount_id%7D~1matches%2Fget)
Before:
After:
=> Additional documentation for '/players/{account_id}/matches'

processors/processExpand.js
This PR fixes the incorrect team value in the `CHAT_MESSAGE_COURIER_LOST` lost event and adds killer and gold bounty information.
Before patch 7.23 (released 2019-11-26), each team only had one courier. The chat event would report `player1` property as the owner team of the courier, 2 for radiant and 3 for dire.
When each player got their own courier, the team property changed to `player2` with `player1` containing the slot of the killer, 0-4 for radiant and 5-9 for dire. For creep/tower killer the value is -1.
---
Related issues: https://github.com/odota/web/issues/3010, https://github.com/odota/web/issues/2778, https://github.com/odota/web/issues/2723, https://github.com/odota/web/issues/2443
=> Update courier death event

routes/spec.js
Fixes incorrect documentation and adds `radiant_score` and `dire_score` fields.
=> Add scores to team matches endpoint and fix docs

routes/objects.js, routes/properties.js, routes/spec.js
Very simple fix - in /benchmarks there are decimal values that are currently typed as integers.
Edit: Fixing more types. Log of changes:
- benchmark metrics from integer to number
- distributions: `dataTypeModifier` from string to integer
- findMatches: input types for teamA and teamB were integers, now array of integers. response type now correct as array
- leagueObject properties should be nullable
- matches required the most updates... summary:
- - player_slot property is nullable
- - objectives, picks_bans, gold_adv and xp_adv are arrays
- - expand cosmetics with item properties
- - additional units is an array and nullable
- - teamfights is a nested array
- - cosmetics here are integers (there are two fields named cosmetics in /matches response, just different nesting)
- - tpscrolls …
=> Fix Swagger Spec definitions

package-lock.json, package.json, routes/requests/queryParams/matchParams.js, routes/spec.js, spec.json
Adds `minRank` and `maxRank` query parameters and uses `avg_rank_tier` field in public_matches to filter results.
```js
"/publicMatches": {
get: {
...
parameters: [
{ $ref: "#/components/parameters/lessThanMatchIdParam" },
{ $ref: "#/components/parameters/minRankParam" },
{ $ref: "#/components/parameters/maxRankParam" },
{ $ref: "#/components/parameters/mmrAscendingParam" },
{ $ref: "#/components/parameters/mmrDescendingParam" },
],
...
route: () => "/publicMatches",
func: async (req, res, cb) => {
...
if (req.query.mmr_ascending) {
order = "ORDER BY avg_rank_tier ASC NULLS LAST";
} else if (req.query.mmr_descending) {
order = "ORDER BY avg_rank_tier DESC NULLS LAST";
} else {
order = "ORDER BY match_id DESC";
moreThan = 0;
}
let minRank= req.query.min_rank
? `AND avg_rank_tier >= …
```
=> Add `minRank` and `maxRank` query parameters to `/publicMatches`

package-lock.json, package.json, routes/responses/schemas/match/PublicMatchesResponse.js, spec.json, store/queries.js
`getHeroItemPopularity` can error if item.time is null. #2663
Also adjust cost thresholds used in defining early, mid, and late game items. See review comments
=> Handle null item times and adjust cost thresholds in `getHeroItemPopularity`

processors/performanceOthers.mjs
Level 15 Talent Half Track Bonus Speed to Allies replaced with to +45 Track Gold
Level 25 Talent +250 Track Gold replaced with No Cooldown on Jinada
I'm assuming that the constant identifier for the lvl 15 talent has remained the same.
=> Update track gold change for 7.35

global.d.ts, routes/api.ts, store/queries.ts, test/test.ts
fixes #2645 
Return an empty array for player endpoints if the player has unchecked Expose Public Match Data and we've picked up the change via profile refresh.
If the player is logged in and matches the account_id of the player being requested, return data normally.
=> Hide data for players with match history disabled

global.d.ts, routes/responses/MatchResponse.ts, sql/create_tables.sql
Adds the ability to track the neutral tokens drops
Related odota/parser PR - https://github.com/odota/parser/pull/72
=> feat: add neutral_token drops data

global.d.ts, routes/responses/MatchResponse.ts, sql/create_tables.sql
Adds ability to track all neutral items player had in match and their enhancements
Related to this PR odota/parser#75
=> Neutral items history

dev/copyUsage.ts, fetcher/getGcData.ts, routes/api.ts, routes/keyManagement.ts, routes/spec.ts, store/queue.ts, svc/buildsets.ts, svc/counts.ts, svc/parser.ts, svc/web.ts, util/buildStatus.ts, util/insert.ts, util/utility.ts
Following up from this discord chat: https://discord.com/channels/144629812982448128/144629812982448128/1349940912205070380
Timestamp processing should use UTC, and `moment()` uses local time be default. So this PR just replaces all usages of `moment()` with `moment.utc()`
=> :recycle: Refactor timestamp handling to use UTC

util/utility.ts
The `averageMedal` method used for computing the average of a set of ranks is very slightly incorrect. We basically treat the ranks as if they are base 5 numbers, and average them based on that. The issue is that rank  are only *almost* base 5 numbers. the second digit is 1-5, when in a base 5 number it would be 0-4. This PR updates the method to account for that so that they get averaged properly.
Here is an example of a scenario where the current implementation is incorrect: 
```js
var ranks = [ 14, 15, 21 ]; // Herald 4, Herald 5, Guardian 1
// EXPECTED AVERAGE: 15 (Herald 5)
// before this PR
console.log(averageMedal(ranks)) // PRINTS: 21 (Guardian 1)
// after this PR
console.log(averageMedal(ranks)) // PRINTS: 15 (Herald 5)
```
=> Fix averageMedal calculation
